/**
 * Core type definitions for Maestro orchestration platform
 */

export type ProjectStatus = 'active' | 'paused' | 'complete';
export type TaskStatus = 'todo' | 'in-progress' | 'done' | 'blocked';
export type AgentStatus = 'active' | 'idle' | 'offline';
export type TaskPriority = 1 | 2 | 3 | 4 | 5;

/**
 * Project representing an autonomous app being built by agents
 */
export interface Project {
  project_id: string;
  name: string;
  description: string;
  github_repo?: string;
  local_path?: string;
  status: ProjectStatus;
  created_date: string;
  agent_count: number;
  task_count?: number;
}

/**
 * Task assigned to agents for execution
 */
export interface MaestroTask {
  task_id: string;
  project_id: string;
  title: string;
  description: string;
  ai_prompt: string;
  assigned_to_agent: string;
  priority: TaskPriority;
  status: TaskStatus;
  created_date: string;
  started_date?: string;
  completed_date?: string;
  blocked_reason?: string;
}

/**
 * Agent working on project tasks
 */
export interface Agent {
  agent_id: string;
  project_id: string;
  agent_name: string;
  status: AgentStatus;
  last_poll_date?: string;
  tasks_completed: number;
  tasks_in_progress: number;
}

/**
 * Request to generate a task prompt via AI
 */
export interface GeneratePromptRequest {
  title: string;
  description?: string;
}

/**
 * Response from AI prompt generator
 */
export interface GeneratePromptResponse {
  prompt: string;
}

/**
 * Pagination helpers
 */
export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  per_page: number;
}

/**
 * API error response
 */
export interface ApiError {
  error: string;
  message: string;
  status: number;
}

/**
 * Improvement suggestion statuses
 */
export type SuggestionStatus = 'pending' | 'approved' | 'rejected' | 'implemented';

/**
 * Improvement suggestion categories
 */
export type SuggestionCategory =
  | 'error-handling'
  | 'performance'
  | 'ux'
  | 'code-quality'
  | 'security';

/**
 * Improvement suggestion priority
 */
export type SuggestionPriority = 'high' | 'medium' | 'low';

/**
 * Improvement Suggestion
 * Generated by Product Improvement Agent for codebase improvements
 */
export interface ImprovementSuggestion {
  id: string;
  project_id: string;
  title: string;
  description: string;
  reasoning: string;
  impact_score: 1 | 2 | 3 | 4 | 5;
  effort_estimate: string;
  files_affected: string[];
  agent_type: string;
  priority: SuggestionPriority;
  category: SuggestionCategory;
  status: SuggestionStatus;
  created_at: string;
  created_by: string;
  approved_at?: string;
  approved_by?: string;
  rejected_at?: string;
  rejected_by?: string;
  implemented_at?: string;
  task_id?: string;
}

/**
 * Event Audit Log
 * Tracks all events in the system for debugging and analytics
 */
export interface EventAuditLog {
  id: string;
  event_type: string;
  payload: Record<string, any>;
  timestamp: string;
  source?: string;
  status: 'triggered' | 'processing' | 'completed' | 'failed';
  error_message?: string;
  duration_ms?: number;
}
